### ISSUE TITLE
Publish as a NuGet package

### ISSUE THREAD

**Issue by nikeee** [nikeee/TeamSpeak3QueryAPI#13]
See title

**Comment by nikeee** [comment]
Good reminder! I'll do this tomorrow.

**Comment by nikeee** [comment]
It is now published under:
https://www.nuget.org/packages/TeamSpeak3QueryApi/1.0.0

Please verify that it works and we can close this issue.

**Comment by MaximilianAst** [comment]
It is working, Thx 👍 

![image](https://user-images.githubusercontent.com/13467300/40247705-91b2e9b0-5acd-11e8-98e5-4c5576767645.png)
