### ISSUE TITLE
Get Clients with more parameters

### ISSUE THREAD

**Issue by lgund** [nikeee/TeamSpeak3QueryAPI#14]
Hey is it possible to get the Clientlist with more parameter like just 1 ?

`var ClientList = await server.teamspeak.GetClients(GetClientOptions.Groups);`

Here just with the Groups Parameter, but I want 2 ;)

**Comment by Splamy** [comment]
Use Bitwise or:
`await server.teamspeak.GetClients(GetClientOptions.Groups | GetClientOptions.Uid | ...);`

**Comment by lgund** [comment]
Worked ;)
