### ISSUE TITLE
Use ushort instead of short for port variable

### ISSUE THREAD

**Issue by almdandi** [nikeee/TeamSpeak3QueryAPI#17]
Hallo,

i found a little mistake. It's not possible to use a query port above 32767 because of variable type `short`. Replacing it with a `ushort` solves the issue.

Thank you and greed work

**Comment by nikeee** [comment]
Good catch! I fixed this in cfb4395. We are now using an `int` (unsigned integers are not CLS compliant). Also, the .NET TcpClient also uses `int`.
