### ISSUE TITLE
get group clients

### ISSUE THREAD

**Issue by adomnits** [nikeee/TeamSpeak3QueryAPI#20]
Is there a way to get group clients?
If not, how this can be added?

**Comment by nikeee** [comment]
What exaclty do you mean by that?
These docs contain a list of all supported commands: http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

If the thing you want to do is listed somewhere in there, we have two options:
- Use the `QueryClient` and pass the parameter losely-typed
- Implement the corresponding wrapper function in `TeamSpeakClient` (that's what I'd prefer)

**Comment by adomnits** [comment]
Following documented function is not implemented in TeamSpeakClient:
SERVERGROUPSBYCLIENTI D
Displays all server groups the client specified with cldbid is currently residing in.
Syntax:
servergroupsbyclientid cldbid={clientDBID}
Example:
servergroupsbyclientid cldbid=18
name=Server\sAdmin sgid=6 cldbid=18
error id=0 msg=ok

I have added support of this function to TeamSpeakClient, but getting below status during call:
Id = 14, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

**Comment by nikeee** [comment]
>  Id = 14, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

This looks like a `Task.ToString()` how did you implement this?

**Comment by adomnits** [comment]
public Task ServerGroupsByClientId(int clientId)
        {
            return Client.Send("servergroupsbyclientid", new Parameter("cldbid", clientId));
        }

**Comment by nikeee** [comment]
In terms of sending the request, this is correct. However, the response is not getting processed.

I just implemented it in this branch: https://github.com/nikeee/TeamSpeak3QueryAPI/compare/servergroupsbyclientid?expand=1
Could you try to use this implementation and verify that it works? I currently don't have a server for myself, so I can't test this implementation.

Usage:
```
var groups = await client.GetServerGroups(clientDatabaseId);
foreach(var g in groups)
    Console.WriteLine(g.Name);
```
Keep in mind that the command requires the **database** ID of the client, not the thing that is referred to as *client id*, which is session-specific. For convenience, you may also pass an Instance of `WhoAmI` or `GetClientsInfo`.

**Comment by adomnits** [comment]
Thank you very much nikeee for so quick response!
Updating my code accordingly.

**Comment by adomnits** [comment]
btw,
ublic Task<IReadOnlyList<GetServerGroup>> GetServerGroups(GetClientInfo clientInfo) => GetServerGroups(clientInfo.DatabaseId);
should be fixed as?
ublic Task<IReadOnlyList<GetServerGroup>> GetServerGroups(GetClient**# s**Info clientInfo) => GetServerGroups(clientInfo.DatabaseId);

**Comment by adomnits** [comment]
working well! Thank you, nikeee. You made my day
