### ISSUE TITLE
How to use GetClients() with GetClientOptions

### ISSUE THREAD

**Issue by Waterfront97** [nikeee/TeamSpeak3QueryAPI#25]
Hi,

when I use the GetClients() method with GetClientOptions.Groups (or any other enum value) I always get the same simple GetClientInfo object without the group information.

![image](https://user-images.githubusercontent.com/15695124/40304568-87f79048-5cf7-11e8-9c1a-04c9481b615a.png)

**Comment by MaximilianAst** [comment]
Hay,

appearently the feature of the GetClientOptions isn't impelemnted yet (The response class doesn't contain the properties needed).
![image](https://user-images.githubusercontent.com/13467300/40311026-f51accaa-5d0e-11e8-89d1-ff9f366651b7.png)

If you need the infos of a specific client you can use one of theese methods in the latest master branch (isn't available throug nuget atm. but can be pushed there if needed)
![image](https://user-images.githubusercontent.com/13467300/40310786-3bfcf81a-5d0e-11e8-98da-ae3eb8eb2683.png)

If you need the info for all clients you can use a litte workaround like this:
![image](https://user-images.githubusercontent.com/13467300/40310981-ce6eea14-5d0e-11e8-82f3-84d988f28919.png)

@nikeee we could probably merge the `GetClientDetailedInfo` class into the `GetClientInfo` class and make the optional field `nullable`  if needed? what do you think?

**Comment by nikeee** [comment]
> we could probably merge the GetClientDetailedInfo class into the GetClientInfo class and make the optional field nullable if needed? what do you think?

I think it would be consistent if we have one Data-Object for each possible Response. I don't want to mix stuff. When they are distingt, it is clear that the property does not exist. Otherwise, people wonder why some properties are not set.

> Or probablly merge all fields (which can be returned from both) into GetClientInfo and let inherit GetClientDetailedInfo from it

Why inherit, if the child class does not add anything new?

Btw:
You sould avoid `.Result` and use the await pattern instead:
```
var clientInfo = await _ts3Client.GetClientInfo(client);
```
So you don't block the current thread. This is especially important if you're in a GUI or handling requests on a server.

**Comment by MaximilianAst** [comment]
Yea there isn't a problem about the enum itself. But the additional fields coming with i.e. the `-groups`  parameter aren't yet mapped into `ClientInfo`.

**Comment by nikeee** [comment]
Is this urgent? We can look at this next week.

**Comment by MaximilianAst** [comment]
No, I don't think so. If I have spare time, I'll take a deeper look into it and make a pull reauest. :)

**Comment by Waterfront97** [comment]
Ty for your fast response!
I build the latest nuget from master to use the `GetClientInfo`
