### ISSUE TITLE
Adding Dictionarry<sting, sting> to Respone

### ISSUE THREAD

**Issue by MaximilianAst** [nikeee/TeamSpeak3QueryAPI#26]
Hay Nikeee what do you think about adding a `Dictionarry<sting, sting>` (or `IReadOnlyList<KeyValuePair<string, string>>`) to the respone class for all respone-parameters that couln't be deserialized?

**Comment by nikeee** [comment]
Do you have a specific use-case in mind? I'd prefer having them serialized, if it is known that the response will have them.

**Comment by MaximilianAst** [comment]
For properties, we didn't considered yet, but are awailabe through teh API. To prevent s.th. lilke in #25 (at least parcially)

**Comment by nikeee** [comment]
If these properties are implemened in the following release, the existing code would break if they update the dependency (or if it's a patch/minor release, if they re-install the dependeny).

I'd just prefer to implement these things correctly in the first place.

**Comment by MaximilianAst** [comment]
Okay :) than you can close this issiue

**Comment by nikeee** [comment]
I opened #28 that covers this concept in a similar way: How about including not only the unprocessed, but *all* fields? This would eliminate compability issues.
We can discuss further ideas in #28.
