### ISSUE TITLE
rc.UseServer 'An error occured during the query'

### ISSUE THREAD

**Issue by callumarmitage** [nikeee/TeamSpeak3QueryAPI#34]
```
An error occurred during the query.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at TeamSpeak3QueryApi.Net.QueryClient.<Send>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HydroBot.Hydrobot.<ConnectToTeamspeak>d__1.MoveNext()
```

If you want to re-produce, use the code below.
```csharp
var rc = new TeamSpeakClient("167.114.60.251", 10011);
try
{
    await rc.Connect();
    await rc.UseServer(2);
    var client = await rc.WhoAmI();

}
catch (Exception e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine(e.StackTrace);
}
```

Edit:
This has been tried with logging in previously, it's just excluded from this example for simplicity.

The error is thrown from rc.UseServer() and it's thrown by connecting to any server Id other than 1.

**Comment by callumarmitage** [comment]
That's the full stack trace obtained from Console.WriteLine(e.StackTrace) so as far as I'm aware that's it.

With regards to the virtual server, the Id's I've tested are ripped straight from the old Java client I'm trying to port into C# so the Ids should be fine. All the information I can attain from it regarding the stack is in the original report.

**Comment by nikeee** [comment]
A `QueryError` is only thrown if the TeamSpeak server responds with an error code that is non-zero. The message of this exception is also taken from that response. So the `server is not running` message actually comes from the server. Maybe you should consult the TeamSpeak support on this one. Or - if you want - you can provide a docker setup for reproduction of this issue, so I can debug this error better.

**Comment by callumarmitage** [comment]
Alright, I've got to the bottom of the issue. The old API i was using used the servers port as the virtual server Id whereas this one is using some arbitrary number. I've managed to find the correct server Id by doing an incremental search. 

For future reference, could a feature be added where we can select the servers port as a connection Id as opposed to the raw Id of the server as there's no way for me to figure out said server Id (to my understanding).

**Comment by nikeee** [comment]
This API is just a wrapper for the query API provided by the server. `UseServer` is not specific to this library, it actually sends a command to the server and is associated with the session.

You should be able to look up the virtual server ID in the database of the server (if you have access to it). Also, the API provided a `serverlisf` method that lists all virtual servers in the server. I don't know if the rich client supports it at the moment. However, using the bare QueryClient, it should work. If it's not supported in TeamSpeakClient, this is definitely a missing feature.

**Comment by MaximilianAst** [comment]
as a side note:

> I've managed to find the correct server Id by doing an incremental search and just connecting to servers until I got the right one.

@callumarmitage instead of brute-forcing you could use `TeamSpeakClient.GetServers()` and the property `GetServerListInfo.Id` should be the virtual server Id

**Comment by nikeee** [comment]
Thanks for mentioning that!
