### ISSUE TITLE
Prerelease nuget deploy after check-in on master

### ISSUE THREAD

**Issue by MaximilianAst** [nikeee/TeamSpeak3QueryAPI#36]
How about deploying a prerelease automatically to nuget with each master-branch build. The release versions could be deployed manually?

**Comment by nikeee** [comment]
I will see if we can do this.

**Comment by MaximilianAst** [comment]
A prerelease nuget  is only defined through the nuget version. If you append `-beta1` `-beta2` (--> `1.0.1-beta1`)and so on it count as prerelease:
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

**Comment by nikeee** [comment]
We now release every push to `master`. The version is generated according to Semver spec:
E. g. `1.9.0-beta.1`, where the last `1` is the number of commits to master since last tag.

**Comment by MaximilianAst** [comment]
Wow Amazing
