### ISSUE TITLE
wie funktioniert es?

### ISSUE THREAD

**Issue by sysworx** [nikeee/TeamSpeak3QueryAPI#37]
Ich verstehe nicht wirklich wie diese API funktioniert...

ich hab es in vb.net so versucht:
```
Dim ts3server As New Net.Specialized.TeamSpeakClient("127.0.0.1", "10011")
ts3server.Login("serveradmin", "pw")
ts3server.UseServer(2)
ts3server.Client.Connect()
MsgBox(ts3server.Client.IsConnected)
```
Ich bekomme da immer false, die angaben stimmen aber :(

**Comment by nikeee** [comment]
Du musst die Aufrufe awaiten, da sie asynchron sind und Tasks zurückgeben. Wenn du das nicht machst, wird die MagBox angezeigt, bevor sich der Client verbunden hat.

```vb.net
Dim ts3server As New Net.Specialized.TeamSpeakClient("127.0.0.1", "10011")
Await ts3server.Login("serveradmin", "pw")
Await ts3server.UseServer(2)
Await ts3server.Client.Connect()
MsgBox(ts3server.Client.IsConnected)
```

Die Methode, die dies beinhaltet, muss dementsprechend als `Async` gekennzeichnet sein.
