### ISSUE TITLE
Feature: Add support for net45

### ISSUE THREAD

**Issue by Maxedome** [nikeee/TeamSpeak3QueryAPI#41]
Im unable to install this in a net45 project.
missing assemblyinformation

**Comment by nikeee** [comment]
Currently, the library targets .NET Standard 1.3. This means .NET FW 4.6 is supported.
See: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support
Maybe I can bring it down to .NET Standard 1.2 / FW 4.5.1. 4.5.0 would be out of scope. Is there any other option on you side?

**Comment by Ubuntuworld** [comment]
IT would be just nice, not a must have. Its for exaple much easier to install net45 in wine.

**Comment by nikeee** [comment]
Well, you could also use .NET Core which runs natively on Linux/macOS.

**Comment by Ubuntuworld** [comment]
Im using another libary, thats Not supporting dotnet core i think. I need to Check that.

**Comment by nikeee** [comment]
Thats weird. .NET Core has a larger API surface as .NET FE 4.5. Probably they don't offer any binaries for FW 4.5.

**Comment by Ubuntuworld** [comment]
Im using WPF and if i understand your comment correct, thats a problem.

**Comment by MaximilianAst** [comment]
@Ubuntuworld I don't know what you want to achive with your application, but if you want to share it that different people to connect to a specific ts3 server, it could be a good idea to make a back-end service, which manages the ts3 connection and expose the information through a rest interface (then netcore 2.0 would be an option for the back-end service).

**Comment by Ubuntuworld** [comment]
@MaximilianAst It looks like thats going to start a discussion about my project. That shouldn't be the problem here. If its not possible or to much work, then its just fine and not that important. Thanks anyways.

**Comment by nikeee** [comment]
This project will be upgraded to C# 8. This likely means that we might require a higher .NET Standard. So this issue will be a wontfix.

Side note: WPF is now available for .NET Core. Maybe you want to look into that.
