### ISSUE TITLE
How to handle Channel Joined event?

### ISSUE THREAD

**Issue by VollRahm** [nikeee/TeamSpeak3QueryAPI#42]
I'm trying to subscribe to the Event where a user joins inside a channel. This is my approach:
```
ts3.Subscribe<ClientEnterView>(data =>
            {
                foreach (var c in data)
                {
                    Console.WriteLine(c.NickName);
                }
            });
```

When i connect to the server it show my Name, but when i switch channels it doesn't do anything.

**Comment by VollRahm** [comment]
It works with ClientMoved, but when i switch some channels it stops working.
I Registered all Channel and Server Notifications.

**Comment by nikeee** [comment]
I think it's the correct way to do it like this.
It shows your name when you connect to a server because the Query Client itself resides in the initial channel. In fact, you can turn on that query clients are shown in the GUI clients.
