### ISSUE TITLE
addservergroup not there?

### ISSUE THREAD

**Issue by crygamerger** [nikeee/TeamSpeak3QueryAPI#47]
Hey,
i dont find a function to give server groups to people in the rich client, is it not included or am i blind?
I dont want to use the middleware.

Thank you

**Comment by nikeee** [comment]
The rich client does not have that many features, since we have to implement every command by hand. If it is missing, feel free to submit a PR and we'll get it in there!

**Comment by nikeee** [comment]
@ceeno2k did some implementation in #49. Does this suffice for your use case?
