### ISSUE TITLE
Send Plugin Command

### ISSUE THREAD

**Issue by nonameShadow** [nikeee/TeamSpeak3QueryAPI#5]
I haven't found any references of SendPluginCommand in documentation, so the question:
is there any way to send command to plugin using this API?

**Comment by nikeee** [comment]
This is an API for the TeamSpeak Query API. `SendPluginCommand` seems to be part of the plugin API, which is a different API. So no, this isn't possible.

**Comment by nonameShadow** [comment]
I was afraid of that :(
Anyway, thanks for the answer!
