### ISSUE TITLE
Not getting any response

### ISSUE THREAD

**Issue by eduardohf14** [nikeee/TeamSpeak3QueryAPI#56]
When the script arrives at the line "await qc.Send" it freezes and goes no further. If I remove await, the whole code processes, however, I do not receive any messages on the console. And it doesn't even enter the callback breakpoint. What am I doing wrong? By the way, the only thing I've been able to do so far, was connect and send a message on the channel.

```csharp
static async Task test2()
        {
            var qc = new QueryClient("localhost", 25639);
            await qc.Connect();

            await qc.Send("clientnotifyregister", new Parameter("schandlerid", 0), new Parameter("event", "notifytextmessage"));
            await qc.Send("clientnotifyregister", new Parameter("schandlerid", 0), new Parameter("event", "notifyclientpoke"));

            qc.Subscribe("notifytextmessage", (data =>
            {
                foreach (var c in data.Payload)
                {
                    Trace.WriteLine("Client " + c.ToString() + " joined.");
                    Console.WriteLine("Client " + c.ToString() + " joined.");
                }
            }));

            qc.Subscribe("notifyclientpoke", (data =>
            {
                foreach (var c in data.Payload)
                {
                    Trace.WriteLine("Client " + c.ToString() + " joined.");
                    Console.WriteLine("Client " + c.ToString() + " joined.");
                }
            }));
        }
```

**Comment by nikeee** [comment]
Habe you tried using the TeamSpeakClient?

**Comment by eduardohf14** [comment]
Yes @nikeee. It freezes on the first await rc.RegisterTextServerNotification ();


`static async Task newTest()
        {
            TeamSpeakClient rc = new TeamSpeakClient("localhost", 25639);
            await rc.Connect();
            Console.WriteLine("Done");

            await rc.RegisterTextServerNotification();
            await rc.RegisterTextPrivateNotification();

            rc.Subscribe<TextMessage>(data => data.ForEach(msg => Console.WriteLine($"Event - Message: {msg.Message}, From: {msg.InvokerName}, Type: {msg.TargetMode}")));

            Console.WriteLine("Done");

            await Task.Delay(10000);

            await rc.SendGlobalMessage("Global Test 1");

            await Task.Delay(10000);

            await rc.SendGlobalMessage("Global Test 2");    

            while (true)
            {
                await Task.Delay(100);
                //Thread.Sleep(100);
            }
        }`

**Comment by eduardohf14** [comment]
Using telnet 127.0.0.1 25639 on the Windows console everything works. Is there any configuration that I'm missing?

**Comment by nikeee** [comment]
Do you use `Thread.Sleep` somewhere in your application? Make sure you always use `Task.Delay` instead of `Thread.Sleep` in your entire code base.

**Comment by eduardohf14** [comment]
> Do you use `Thread.Sleep` somewhere in your application? Make sure you always use `Task.Delay` instead of `Thread.Sleep` in your entire code base.

No. I do not use any Thread.Sleep. 

Is that correct? That was the only way I was able to connect

`TeamSpeakClient rc = new TeamSpeakClient("localhost", 25639);`

 When I don't use port 25639 I get error: 

> SocketException: No connections could be made because the target machine actively refused them 127.0.0.1:10011

**Comment by nikeee** [comment]
> on the Windows console everything works

Could you specify "eerything"?

> When I don't use port 25639 I get error:

You have to use the port that the query server runs on.

When reading [this](
https://www.myteamspeak.com/addons/943dd816-7ef2-48d7-82b8-d60c3b9b10b3):
> The ClientQuery plugin offers a local telnet interface on port 25639 to remotely control the TeamSpeak 3 Client.

This library is for controlling the server, not the client.

**Comment by eduardohf14** [comment]
> > on the Windows console everything works
> 
> Could you specify "eerything"?
> 
> > When I don't use port 25639 I get error:
> 
> You have to use the port that the query server runs on.
> 
> When reading [this](https://www.myteamspeak.com/addons/943dd816-7ef2-48d7-82b8-d60c3b9b10b3):
> 
> > The ClientQuery plugin offers a local telnet interface on port 25639 to remotely control the TeamSpeak 3 Client.
> 
> This library is for controlling the server, not the client.

![Sem título2](https://user-images.githubusercontent.com/20343381/89109161-14684180-d415-11ea-8d99-ad4614538121.png)

> This library is for controlling the server, not the client.
damn, I can't use this on my computer to read my received messages and pokes? I'm not the owner of the server.

**Comment by nikeee** [comment]
The protocol may be similar. You may try, but it is not supported in any way. You have to use the `QueryClient`, since the rich client is server-only. I don't know how notifications work on the ClientQuery interface.

The greeting banner of a supported endpoint looks like this:
```
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
```

If you find out how it works, I'd be happy to see how you did it.
