### ISSUE TITLE
SSH Support

### ISSUE THREAD

**Issue by lgund** [nikeee/TeamSpeak3QueryAPI#58]
Telnet isnt very safty. Are you planing to add ssh support? Teamspeak will remove for sure telnet support in the future.

**Comment by nikeee** [comment]
Do you have a reference for their raw TCP removal?

**Comment by lgund** [comment]
The syntax is still the same. You just need to use the ssh protocol and for sure you need to login first. So you can connect to the query without a valid login. It´s look like there is currently no c# lib that support this functionality. If you want I can try to add them and make a pull request.

**Comment by nikeee** [comment]
Do you have a reference _on the website of teamspeak or their docs_ that says that SSH is supported?

**Comment by lgund** [comment]
This picture is a ssh connection. You know that teamspeak hasn't god documents. But you can look over the official changelog of the latest server [here](https://community.teamspeak.com/t/teamspeak-server-3-12-x/3916). SSH was added long ago at the begining of the year. Currently they have also added webquery via http and https since march. In my ini file you can add this line to activate all of them `query_protocols=raw,ssh,http,https`.

Edit: I found the [post](https://forum.teamspeak.com/threads/138675-Release-TeamSpeak-3-Server-3-6-0). SSH will be there now by default and raw will be by default disabled. But I am sure this is just a question of time when it will be removed.

**Comment by lgund** [comment]
I´ve added ssh support [here](https://github.com/lgund/TeamSpeak3QueryAPI/tree/ssh). I would make a pr but it would be better in a other branch? There you can check the code and you can publish it as version 2.0 if it works stable enough.

I hope this is a deal. Please let me know if you create a branch.

I´ve added a little prefix so you can see which mode is currently used (SSH or TELNET):
![image](https://user-images.githubusercontent.com/13957661/89720268-6e967300-d9d0-11ea-9412-4d361b11b6d1.png)

Only diffrence is in the login code. All other codes work like before. You just have here the diffrence:
```
    // Ssh connection
    var rc = new TeamSpeakClient(host, TeamspeakConnectionType.SSH);
    rc.ConnectSsh(user, password);

    // Telnet connection
    var rc = new TeamSpeakClient(host);
    await rc.ConnectTelnetAsync();
    await rc.LoginAsync(user, password);
```
