### ISSUE TITLE
Fatal error: Unsubscripe with callback won't work

### ISSUE THREAD

**Issue by lgund** [nikeee/TeamSpeak3QueryAPI#61]
I would make a pr but I can´t refork this project again and I don´t know how can I refork the master branch into my fork. 👎 . So I create this issue and hope @nikeee can fix it with the next commit.

It´s currently not possible to clear a specific subscribe notification cause the callback method can´t be compared with the saved callback methods.

TeamspeakClient.cs:79
=====================
```
    public void Unsubscribe<T>(Action<IReadOnlyCollection<T>> callback)
        where T : Notification
    {
        var notification = GetNotificationType<T>();
        var cbt = _callbacks.SingleOrDefault(t => t.Item1 == notification && t.Item2 == callback as object);
        if (cbt != null)
            Client.Unsubscribe(notification.ToString(), cbt.Item3);
    }
```

`t.Item2 == callback as object` this part of the code will always return false. To fix this you need to use the method `.equals`. I will also fix this in my ssh branch.

Solution
=================
```
    public void Unsubscribe<T>(Action<IReadOnlyCollection<T>> callback)
        where T : Notification
    {
        var notification = GetNotificationType<T>();
        var cbt = _callbacks.SingleOrDefault(t => t.Item1 == notification && t.Item2.Equals(callback));
        if (cbt != null)
            Client.Unsubscribe(notification.ToString(), cbt.Item3);
    }
```

**Comment by nikeee** [comment]
Solved in 9a557e8f31c4609df4cfb7c8dbca6df9f4daa557
