### ISSUE TITLE
Events occasionally do not fire (ClientLeftView,ClientEnterView,TextMessage)

### ISSUE THREAD

**Issue by Arefu** [nikeee/TeamSpeak3QueryAPI#64]
Heya!
```csharp
Instance = new TeamSpeakClient(Host, Port);
Instance.Connect().Wait();
Instance.Login(User, Pass);`
//Select Server & Set Nick
Instance.UseServer(ServerID);
Instance.Client.Send("clientupdate client_nickname=Bitch");

//We Want Server & Server Text Events
Instance.RegisterServerNotification();
Instance.RegisterTextServerNotification();

//Setup Callbacks For My Events
Instance.Subscribe<ClientEnterView>(ClientEnter);
Instance.Subscribe<ClientLeftView>(ClientLeft);
```

This is the code I have currently, at times I've noticed that either the client doesn't connect (and it doesn't throw any error back? Or events aren't registering correctly, am I doing something wrong or am I crazy?

My reproduction was, I compiled the program, launched my TeamSpeak and it saw I joined but wouldn't catch me sending messages, then relaunching it would catch all 3, but then compile again and it wouldn't do anything.

I have my IP in the Server_query_whitelist ip file, also as a side note, does anyone know how to get the 'serve id' that's the string ID?

**Comment by Arefu** [comment]
It also might be apparently disconnecting if idle for to long? Is this a server setting that times them out, or since I'm not doing a whoami loop to stay conected?

**Comment by nikeee** [comment]
The server disconnects an idle client. See: https://github.com/nikeee/TeamSpeak3QueryAPI/issues/7#issuecomment-683739863

**Comment by Arefu** [comment]
Hmm, I do think it's a "bug" but, only because TeamSpeak themselves have made it one, I think the Connect or even Login function should accept an overload for Stay Alive, so it just sends a Who Am I every 5 seconds or so just to stay awake.

I'll hack that in my project, see if it fixes it, if it does I may submit a PR :)

**Comment by nikeee** [comment]
How about a separate class that takes a Client and sends heartbeats? Something kile this:
```csharp
class HeartbeatSender {
    HeartbeatSender(QueryClient client) { ... }
    void StartHeartbeats() {}
    void StopHeartbeats() {}
}

TeamSpeakClient c; // ...
var hb = new HeartbeatSender(c);
hb.StartHeartbeats();
```

Alternatively, we can build this right into the QueryClient. I don't know what the better approach would be.

Any pros and cons of both approaches?

**Comment by Arefu** [comment]
Hmm, the overload idea could work, you could hook it up to a stopwatch behind the scenes for every X seconds specified by the user with a default of 3 so it just sends a who am I?

That's at least what I am going to test with my project now, also any reason why TeamSpeakClient.Client.IsConnected would be false right after calling Connect? Do I need to really await everything in order for it to connect fully?

**Comment by Arefu** [comment]
Hmm, one caveat may be that if we do a keep alive style it may just get stuck waiting for that to finish then just keep stacking up other events which cause that to dead lock, or have I fallen off my rocker

**Comment by Arefu** [comment]
So I rewrote it all in async using [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main) as a point of reference and events seem to be firing now, now sure if coincidence with the time taken to rewrite to lift some rate limit, but either way it works.

I'll report back if I see it get booted for being idle, if so I'll try the Timer elapsed way and let you know.

**Comment by nikeee** [comment]
Having a Timer under the good would require a specific dependency that the library user might not have (and doesn't want to install, just for having a Timer).

I think the more appropriate way of implementing the heartbeat is adding a timeout for some task in the response queue.

**Comment by Arefu** [comment]
Yeah, I figured I could get away with not, like I said, I ended up writing using async and events now work (whoo!) but I still get timed out when not active.

I used the System.Timers.Timer() class (which I'm pretty sure is in .net core so we don't have to worry about people not having the dependency), but it seems that events don't fire with it running, I'm not sure if I'm whack, or I'm doing something wrong, but it appears stuff might get caught in the queue among other things if the timer has elapsed before it fires again

**Comment by nikeee** [comment]
I opened a new issue regarding the timeout feature: #65.
