### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by KLD** [nikeee/TeamSpeak3QueryAPI#7]
After sometime, I lose connection and all query clients disconnect. I get this in debug: 

`line: notifyclientleftview cfid=1 ctid=0 reasonid=3 reasonmsg=connection\slost clid=3`

Note: after clients are disconnected, debug is spammed with many: `line:` with no message.

Sorry and thank you.

**Comment by nikeee** [comment]
Any way to reproduce this?

**Comment by lgund** [comment]
In teamspeak you need to create every X minutes a request otherwise the connection will be closed by teamspeak. So you need to make a `alive` request. I would say it´s not really a bug.
