### ISSUE TITLE
Client times out after 5 mins

### ISSUE THREAD

**Issue by jgoedde** [nikeee/TeamSpeak3QueryApi#82]
Hey,

Exactly after 5 Minutes the bot just disconnects. The app is not crashing, the client just times out.

`<PackageReference Include="TeamSpeak3QueryApi" Version="1.13.0" />`

Tried initializing instance with `keepAliveInterval = TimeSpan.MaxValue,` `TimeSpan.MinValue` and `TimeSpan.FromSeconds(5)`

`new TeamSpeakClient(_teamSpeakOptions.Host, _teamSpeakOptions.QueryPort, TimeSpan.MaxValue);`

Part of connecting:

```
await _teamSpeakClient.Connect();
await _teamSpeakClient.Login(_teamSpeakOptions.User, _teamSpeakOptions.Pass);
await _teamSpeakClient.UseServer(1);

try
{
    var whoAmI = await _teamSpeakClient.WhoAmI();

    await _teamSpeakClient.ChangeNickName(_teamSpeakOptions.Nick, whoAmI);
}
catch (QueryException e)
{
    Console.WriteLine("Unable to change nickname");
}

await _teamSpeakClient.RegisterServerNotification();

_teamSpeakClient.Subscribe<ClientEnterView>(e => HandleClientEnterViewNotification(e, cancellationToken));
```

(What) do I need to pass to `keepAliveInterval`?
For the first 5 minutes the client runs without any issues.

**Comment by jgoedde** [comment]
`<TargetFramework>net7.0</TargetFramework>`

**Comment by JohannesBauer97** [comment]
It was coded that the connection gets closed after 5mins of idletime:
https://github.com/nikeee/TeamSpeak3QueryApi/blob/66ee9294d611a3c2b3273fc24b6315f89d8aa2bd/src/TeamSpeak3QueryApi/Specialized/TeamSpeakClient.cs#L23C73-L23C73

If you need a permanent connection (e.g. listening to events) you can request WhoAmI every 4mins that the idle check doesn't hit.
